services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user01
      POSTGRES_PASSWORD: password01
      POSTGRES_DB: demodb
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"